name=CompileDateHeure
version=1.0.1
author=Olivier FOURNET <olivier.fournet@free.fr>
maintainer=Olivier FOURNET <olivier.fournet@free.fr>
sentence=A simple Arduino library to print the compile date and time.
paragraph=Print the compilation date and time to Serial. Supports Arduino IDE and PlatformIO on ESP8266, ESP32, and other boards.
category=Other
url=https://github.com/Fo170/CompileDateHeure
architectures=*
includes=CompileDateHeure.h
license=GNU GPLv3
description=A simple Arduino library to print the compile date and time. Supports Arduino IDE and PlatformIO. Compatible with ESP8266, ESP32 and other boards.