; Fichier exemple platformio.ini pour tester la librairie CompileDateHeure
; Copiez ce fichier dans le dossier de votre projet PlatformIO

; Pour ESP8266, utilisez :
[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 9600

lib_deps =
    https://github.com/Fo170/CompileDateHeure.git@^1.0.1

; Pour ESP32, utilisez :
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 9600
lib_deps =
    https://github.com/Fo170/CompileDateHeure.git@^1.0.1